version: '3'
services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      - db
    secrets:
      - db-password
    environment:
      - PASSWORD_FILE_PATH=/run/secrets/db-password
      - DB_HOST=db
      - DB_NAME=website
      - DB_USER=root
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html/src
        - action: sync
          path: ./
          target: /var/www/html
  db:
    image: mariadb:lts
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_DATABASE=website
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
volumes:
  db-data:
secrets:
  db-password:
    file: src/Setting/password.txt
